; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_flags =
    -D WIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -D WIFI_PASS=\"${sysenv.WIFI_PASS}\"

; --- ENVIRONMENT 1: First time upload via USB ---
[env:d1_mini_usb]
; Uses default USB serial upload (COM3 in your case)

; --- ENVIRONMENT 2: Wireless OTA upload ---
[env:d1_mini_ota]
upload_protocol = espota
; Replace with your Wemos D1's IP address (shown in Serial Monitor) or hostname
;upload_port = wemos-d1-mini.local
upload_port = 192.168.5.223

; If you enable a password in main.cpp, uncomment the line below:
; upload_flags = --auth=admin123
